name: test_env_model_assessor
channels:
  - conda-forge
dependencies:
  - python=3.9
  ############## These will have to be adjusted to your specific project
  # - cartopy
  # - cf_pandas
  - cf_xarray
  - extract_model
  - intake
  # - intake-axds
  # - intake-erddap
  - matplotlib-base
  - numpy
  - pandas
  - scipy
  - xarray
  ##############
  - pytest
  - pip:
    - alphashape
    - cf_pandas
    - intake-axds
    - intake-erddap
    - tqdm
    - codecov
    - pytest-cov
    - coverage[toml]
