name: omsa_docs
channels:
  - conda-forge
  - defaults
dependencies:
   - python=3.8
   # If your docs code examples depend on other packages add them here
  #  - cartopy
  #  - matplotlib-base
   # - ipython
   # - jupyter
   # - jupyterlab
   - aiohttp
   - cartopy
  #  - cf_pandas
   - cf_xarray
   - extract_model
   - intake
   - intake-xarray
   - numpy
   - pandas
   - xarray
   # These are needed for the docs themselves
   - jupytext
   - numpydoc
   - requests
   - sphinx
   - sphinx-markdown-tables
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - pip
   - recommonmark
   - pip:
     - alphashape
    #  - git+https://github.com/intake/intake
     - cf_pandas
     - intake-axds
     - intake-erddap
    #  - intake-xarray
     - tqdm
    #  - cf-pandas
     - docrep<=0.2.7
     - furo
     - nbsphinx
     - jupyter_client
     - myst-nb
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - sphinxcontrib-srclinks
